---
- name: Install Certbot
  community.general.pacman:
    name: certbot
    state: present

- name: Install certbot automatic renewal unit file
  ansible.builtin.copy:
    src: certbot.service
    dest: /etc/systemd/system/certbot.service
    owner: root
    group: root
    mode: 0644

- name: Install certbot automatic renewal timer file
  ansible.builtin.copy:
    src: certbot.timer
    dest: /etc/systemd/system/certbot.timer
    owner: root
    group: root
    mode: 0644

- name: Enable certbot timer
  ansible.builtin.systemd:
    name: certbot.timer
    enabled: true
    state: started
    daemon_reload: true
