---
- name: Install Certbot
  pacman:
    name: certbot
    state: present

- name: Install certbot automatic renewal unit file
  copy:
    src: certbot/certbot.service
    dest: /etc/systemd/system/certbot.service
    owner: root
    group: root
    mode: 0644

- name: Install certbot automatic renewal timer file
  copy:
    src: certbot/certbot.timer
    dest: /etc/systemd/system/certbot.timer
    owner: root
    group: root
    mode: 0644

- name: Enable certbot timer
  systemd:
    name: certbot.timer
    enabled: true
    state: started
    daemon_reload: true

- name: Set permissions on /var/lib/letsencrypt
  file:
    path: /var/lib/letsencrypt
    owner: root
    group: http
    mode: u=rwx,g=rs,o=rx
    state: directory
