---
- name: Install Certbot
  pacman:
    name: certbot
    state: present

- name: Install certbot automatic renewal unit file
  copy:
    src: certbot.service
    dest: /etc/systemd/system/certbot.service
    owner: root
    group: root
    mode: 0644

- name: Install certbot automatic renewal timer file
  copy:
    src: certbot.timer
    dest: /etc/systemd/system/certbot.timer
    owner: root
    group: root
    mode: 0644

- name: Enable certbot timer
  systemd:
    name: certbot.timer
    enabled: true
    state: started
    daemon_reload: true

- name: Install letsencrypt config for Nginx
  copy:
    src: letsencrypt.conf
    dest: /etc/nginx/conf.d/letsencrypt.conf
    owner: root
    group: root
    mode: 0644
